version: '3.8'
services:
  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "123456" # 配置root用户密码
      MYSQL_DATABASE: "cool" # 业务库名
      MYSQL_USER: "cool" # 业务库用户名
      MYSQL_PASSWORD: "123123" # 业务库密码
  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/
  chatgpt-share-server:
    image: xyhelper/chatgpt-share-server:latest
    restart: always
    ports:
      - 8300:8001
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 接入网关地址
      CHATPROXY: "https://demo.xyhelper.cn"
      # 接入网关的authkey
      AUTHKEY: "xyhelper"
      # 内容审核及速率限制
      AUDIT_LIMIT_URL: "http://chatgpt-share-server-fox:6956/api/auditLimit"
      OAUTH_URL: "http://chatgpt-share-server-fox:6956/api/chatShareServer/oauth"
      APIAUTH: Doraemon
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data/chatgpt-share-server/:/app/data/
    labels:
      - "com.centurylinklabs.watchtower.scope=xyhelper-chatgpt-share-server"
  chatgpt-share-server-fox:
    image: xiaomifengd/chatgpt-share-server-fox:latest
    restart: always
    ports:
      - "8400:6956"
    depends_on:
      - mysql
      - chatgpt-share-server
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cool?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: "" # 如果Redis没有设置密码，保持为空
      O1_PREVIEW_LIMIT: 30 #o1-preview模型限制次数，填写0则不限制
      O1_PREVIEW_PER: 1w # o1-preview模型限制周期 请填写1s,1m,1h,1d,1w,1M,1y的形式
      O1_MINI_LIMIT: 50 #o1-mini模型限制次数，填写0则不限制
      O1_MINI_PER: 1d # o1-mini模型限制周期 请填写1s,1m,1h,1d,1w,1M,1y的形式
      APIAUTH: Doraemon 
    volumes:
      - ./data/chatgpt-share-server-fox/logs/:/tmp/logs
